version: '3'
services:
  mysql-boilerplate-oauth:
    image: mysql:8.0
    container_name: mysql-boilerplate-oauth
    ports:
      - "13806:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate-oauth
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - boilerplate-oauth-mysql-volume:/var/lib/mysql

volumes:
  boilerplate-oauth-mysql-volume:
    driver: local
